import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import { AppDataProvider } from '@/context/AppContext'
import Navbar from './components/Navbar'
import { useAppContext } from '@/hooks/useContexts'
import Wrapper from './components/Wrapper'

// const inter = Inter({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Itsoluwatobby Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildrenNode) {

  return (
    <html lang="en">
      <body className={`hidebars w-full h-screen`}>
        <AppDataProvider>
          <Wrapper>
            <Navbar />
            {children}
          </Wrapper>
        </AppDataProvider>
      </body>
    </html>
  )
}
