export const shell_Commands: ShellCommandsType = {
  "cat": 'CAT',
  "help": 'HELP',
  "ls": 'LS',
  "ls -l": 'LS_LONG',
  "login": 'LOGIN',
  "signin": 'LOGIN',
  "logout": 'LOGOUT',
  "signout": 'LOGOUT',
  "clear": 'CLEAR',
  "echo": 'ECHO',
  "whoami": 'WHOAMI',
  "man": 'MAN',
  "email": 'EMAIL',
  "contact": 'CONTACT',
  "profile": 'PROFILE',
  "git": 'PROFILE',
  "about": 'PROFILE',
  "history": 'HISTORY',
  "commands": 'COMMANDS',
}